package com.rvrk.starter;

import com.rvrk.starter.util.ConnectionManager;
import org.postgresql.Driver;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class GeneratedKeysRunner {
    public static void main(String[] args) throws SQLException {
        Class<Driver> driverClass = Driver.class;

        String sql = """
               INSERT INTO info(data)
               VALUES 
               ('autogenerated')
                """;


        try (Connection connection = ConnectionManager.open();
             Statement statement = connection.createStatement()) {

            System.out.println(connection.getTransactionIsolation());
            System.out.println(connection.getSchema());

            int executeUpdate = statement.executeUpdate(sql,Statement.RETURN_GENERATED_KEYS);
            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()){
                int generatedKeysInt = generatedKeys.getInt("id");
                System.out.println(generatedKeysInt);
            }
        }
    }
}
